name: flux
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.14=h5eee18b_0
  - python=3.10.12=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - aiofiles==23.2.1
    - aliyun-python-sdk-core==2.16.0
    - aliyun-python-sdk-kms==2.16.5
    - altair==5.4.0
    - annotated-types==0.7.0
    - anyio==4.4.0
    - attrs==24.2.0
    - blinker==1.8.2
    - cachetools==5.5.0
    - certifi==2024.7.4
    - cffi==1.17.1
    - charset-normalizer==3.3.2
    - click==8.1.7
    - coloredlogs==15.0.1
    - contourpy==1.2.1
    - crcmod==1.7
    - cryptography==43.0.3
    - cycler==0.12.1
    - diffusers==0.30.1
    - einops==0.8.0
    - exceptiongroup==1.2.2
    - fastapi==0.115.12
    - ffmpy==0.4.0
    - filelock==3.14.0
    - fire==0.6.0
    - flatbuffers==24.3.25
    - flux==0.0.0.post1+g8726236aa
    - fonttools==4.53.1
    - fsspec==2024.6.1
    - gitdb==4.0.11
    - gitpython==3.1.43
    - gradio==5.30.0
    - gradio-client==1.10.1
    - groovy==0.1.2
    - h11==0.14.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - huggingface-hub==0.31.4
    - humanfriendly==10.0
    - idna==3.8
    - imageio==2.36.0
    - importlib-metadata==8.4.0
    - importlib-resources==6.4.4
    - invisible-watermark==0.2.0
    - jinja2==3.1.4
    - jmespath==0.10.0
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - kiwisolver==1.4.5
    - lazy-loader==0.4
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.9.2
    - mdurl==0.1.2
    - mpmath==1.3.0
    - mypy-extensions==1.0.0
    - narwhals==1.5.4
    - networkx==3.3
    - ninja==1.11.1.1
    - numpy==2.1.0
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.6.20
    - nvidia-nvtx-cu12==12.1.105
    - onnxruntime==1.19.2
    - opencv-python==4.10.0.84
    - openxlab==0.1.2
    - optimum-quanto==0.2.4
    - orjson==3.10.7
    - oss2==2.17.0
    - packaging==24.1
    - pandas==2.2.2
    - pillow==10.4.0
    - pip==24.2
    - protobuf==5.27.3
    - pyarrow==17.0.0
    - pycparser==2.22
    - pycryptodome==3.21.0
    - pydantic==2.8.2
    - pydantic-core==2.20.1
    - pydeck==0.9.1
    - pydub==0.25.1
    - pygments==2.18.0
    - pyparsing==3.1.2
    - pyre-extensions==0.0.23
    - python-dateutil==2.9.0.post0
    - python-multipart==0.0.20
    - pytz==2023.4
    - pywavelets==1.7.0
    - pyyaml==6.0.2
    - referencing==0.35.1
    - regex==2024.7.24
    - requests==2.28.2
    - rich==13.4.2
    - rpds-py==0.20.0
    - ruff==0.11.10
    - safehttpx==0.1.6
    - safetensors==0.4.4
    - scikit-image==0.24.0
    - scikit-learn==1.5.1
    - scipy==1.14.1
    - seaborn==0.13.2
    - semantic-version==2.10.0
    - sentencepiece==0.2.0
    - setuptools==60.2.0
    - shellingham==1.5.4
    - six==1.16.0
    - smmap==5.0.1
    - sniffio==1.3.1
    - starlette==0.46.2
    - streamlit==1.37.1
    - streamlit-keyup==0.2.4
    - sympy==1.13.2
    - tenacity==8.5.0
    - termcolor==2.4.0
    - threadpoolctl==3.5.0
    - tifffile==2024.9.20
    - timm==0.3.2
    - tokenizers==0.19.1
    - toml==0.10.2
    - tomlkit==0.12.0
    - torch==2.4.0
    - torchvision==0.19.0
    - tornado==6.4.1
    - tqdm==4.65.2
    - transformers==4.44.2
    - triton==3.0.0
    - typer==0.12.4
    - typing-extensions==4.12.2
    - typing-inspect==0.9.0
    - tzdata==2024.1
    - urllib3==1.26.20
    - uvicorn==0.30.6
    - watchdog==4.0.2
    - websockets==12.0
    - wheel==0.43.0
    - zipp==3.20.1
